### ISSUE TITLE
How Do I use it?

### ISSUE THREAD

**Issue by cardchase** [S1M0N38/soccerapi-server#1]
After running `docker run -p 5000:5000 s1m0n38/soccerapi` I have it running.
How do I go further to extract BET365 odds now?
A complete noob here with Docker. Sorry if I am asking a beginner question.

**Comment by S1M0N38** [comment]
This program is not for extraction odds. It generate headers required to scrape bet365 and can be use with [soccerapi](https://github.com/S1M0N38/soccerapi). The latter is the library that you are looking for.
