### ISSUE TITLE
TimeoutError: Navigation timeout

### ISSUE THREAD

**Issue by dimkar121** [S1M0N38/soccerapi-server#5]
Hallo,
I am running the docker image but after a minute (without any calls), I get the following:

> soccerapi-server@0.0.1 start

> node index.js

Node.js web server at port 5000 is running..

/app/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:120

rejectCallback(new Errors_js_1.TimeoutError('Timeout exceeded while waiting for event'));

^
TimeoutError: Timeout exceeded while waiting for event
at Timeout.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:120:28)
at listOnTimeout (node:internal/timers:556:17)
at processTimers (node:internal/timers:499:7)
npm notice
npm notice New minor version of npm available! 7.5.1 -> 7.11.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.11.2
npm notice Run npm install -g npm@7.11.2 to update!
npm notice
npm ERR! code 1
npm ERR! path /app
npm ERR! command failed
npm ERR! command sh -c node index.js
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-05-03T12_11_14_718Z-debug.log

thanks
D.

**Comment by dimkar121** [comment]
I found the problem, machines from my country of residence are not eligible to access bet365.com

**Comment by S1M0N38** [comment]
Yes, that's the problem. Moreover many (if not all) VPN service are detected by bet365 and the same error would rise.

**Comment by dimkar121** [comment]
Is there any way to configure the extension (bet365.com to bet365.gr etc)?

**Comment by S1M0N38** [comment]
You can clone this repo, try to change https://github.com/S1M0N38/soccerapi-server/blob/474c8cc85a575e7e8b5e78f8e188b3374af65f62/index.js#L46 to `bet365.gr` and then rebuild the docker locally
